### ISSUE TITLE
Simulate delay

### ISSUE THREAD

**Issue by supermax45** [cflurin/homebridge-shims#1]
Hey @cflurin, I have followed the newest API using your shims as guidelines to simulate a window profile.

Almost everythings works. The only thing I need to get a perfect simulation is to add some delay to the currentposition after setting a targetposition.

Example:
Setting targetposition to 10% and in the app see that the currentpositons shows 1%-2%...-10% with maybe 500ms between each addiction.

I have tried this:

if(value > this.currentValue.CurrentPosition)
	{
	temp = value;
	for(i = 0; i < 10; i++) {
		setTimeout(function() {
		 this.currentValue.CurrentPosition += 1;
		 this.currentValue.PositionState = 1;
		 this.Characteristic.PositionState.setValue(this.currentValue.PositionState);
		 this.Characteristic.CurrentPosition.setValue(this.currentValue.CurrentPosition);

		 this.Characteristic.CurrentPosition.setValue(this.currentValue.CurrentPosition);
		}.bind(this), 500);
	}
But this doesn't work as attended. 

Can you tell if it's possible to accomplish this task? and maybe how?

Thanks :)

**Comment by cflurin** [comment]
Take a look [here](https://nodejs.org/api/timers.html) and FhemLightbulb.js.

**Comment by supermax45** [comment]
Sry for being dumb but can't find anything that helps me. Do you refer to your setBrightnes fuction?

Should i call callback everytime in the for loop to update the display each % instead of every 10 %?

setTargetPosition: function(value, callback) {
    this.log("setTargetPosition: " + value);
    this.currentValue.TargetPosition = value;
    this.setCurrentPosition(value);
    callback();


  },

**Comment by cflurin** [comment]
setBrightness shows how to use the Timer() function.
I see what your are looking for but I didn't implement such as simulation inside homebridge yet.
This example might help you: (https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/TemperatureSensor_accessory.js)

**Comment by supermax45** [comment]
Already looked at that example, but it isn't gonna solve anything. 

Also tried to install npm module sleep and set the function to sleep in the for loop, but nothing updates. It seems like it's only updating then callback() is called, as seen in my lastest comment.

But i get errors if i put callback in the for loop.

I also tried to make a for loop around 
this.setCurrentPosition(value);
callback();
So this get called more often but it still only run setCurrentPosition function one time (I can see it at consol logs).

**Comment by supermax45** [comment]
Nevermind it works now! forgot to change currentposition setprops stepvalue to 1 -.- stupid me.

**Comment by cflurin** [comment]
I've forgot to mention :zap: , there is an example about time simulation > [LockMechanism.js] (https://github.com/cflurin/homebridge-shims/blob/master/LockMechanism.js)
