### ISSUE TITLE
Issue installing homebridge

### ISSUE THREAD

**Issue by ekwarg** [cflurin/homebridge-shims#3]
Hello, I encountered some problem installing Homebridge, here are the results for uname -a, gcc --version and package json. 

I'll add the error encountered at npm -install at the very bottom.

uname -a
Linux raspberrypi 4.1.11-v7+ #822 SMP PREEMPT Fri Oct 23 16:22:18 BST 2015 armv7l GNU/Linux

gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

package.json
{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {

"telldus-live": "^0.2.1",
     
    "color": "0.10.x",
    "hap-nodejs": "^0.0.2",
    "mdns": "^2.2.4",
    "node-persist": "0.0.x",
    "q": "1.4.x",
    "request": "2.49.x",
    "xml2js": "0.4.x",
    "xmldoc": "0.1.x",
    "debug": "^2.2.0"
  }
}

Error:

npm install
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'node persist' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'homebridge'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.1.11-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/node-v4.2.1-linux-armv7l/homebridge
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node-v4.2.1-linux-armv7l/homebridge/npm-debug.log
npm ERR! not ok code 0

Hope you can help!

**Comment by cflurin** [comment]
```sh
npm ERR! node -v v0.10.29
```
You have to install the latest node version. See Wiki.

**Comment by ekwarg** [comment]
Thanks! Have now installed the latest version of node but get this as a when I do the npm install of homebridge:

pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm install
npm ERR! addLocal Could not install /home/pi/node-v4.2.1-linux-armv7l/homebridge/node persist@0.0.x
npm ERR! Linux 4.1.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/pi/node-v4.2.1-linux-armv7l/homebridge/node persist@0.0.x
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/node-v4.2.1-linux-armv7l/homebridge/node persist@0.0.x'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-v4.2.1-linux-armv7l/homebridge/npm-debug.log
pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm install
-bash: pi@raspberrypi: command not found
pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm ERR! addLocal Could not install /home/pi/node-v4.2.1-linux-armv7l/homebridge/node persist@0.0.x

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/pi/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.14.7 /usr/local/lib/node_modules/npm





The package.json is the same as the one posted previously.

There seems to be a problem with node persist.

**Comment by cflurin** [comment]
```sh
pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm install
````
you have to run "npm install" inside the homebridge folder.
Please delete your homebridge folder and start the installation according to the wiki, step by step.

**Comment by ekwarg** [comment]
I swear to be following all steps thoroughly. now got this error.

pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.1.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! file /home/pi/node-v4.2.1-linux-armv7l/homebridge/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 26:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /home/pi/node-v4.2.1-linux-armv7l/homebridge/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-v4.2.1-linux-armv7l/homebridge/npm-debug.log

**Comment by cflurin** [comment]
Got to your home dir
```sh
cd $home
```
and run
```sh
pi@raspberrypi ~$ ls -l
```
post the output

**Comment by ekwarg** [comment]
the output is:

pi@raspberrypi ~ $ cd $home
pi@raspberrypi ~ $ pi@raspberrypi ~$ ls -l
-bash: pi@raspberrypi: command not found

**Comment by cflurin** [comment]
hmm! type only the command!!!
```sh
ls -l
```
If you are new to Raspbian(linux) please have a look [here](https://www.raspberrypi.org/)

**Comment by ekwarg** [comment]
Sorry, I am very new to this..

pi@raspberrypi ~ $ ls -l
total 32288
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Desktop
drwxr-xr-x 5 pi pi     4096 Jan  1  1970 Documents
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Downloads
drwxr-xr-x 5 pi pi     4096 Oct 28 19:48 HAP-NodeJS
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Music
drwxr-xr-x 7 pi pi     4096 Oct 29 09:12 node-v4.2.1-linux-armv7l
-rw-r--r-- 1 pi pi 11003942 Oct 13 19:19 node-v4.2.1-linux-armv7l.tar.gz
-rw-r--r-- 1 pi pi 11003942 Oct 13 19:19 node-v4.2.1-linux-armv7l.tar.gz.1
-rw-r--r-- 1 pi pi 11003942 Oct 13 19:19 node-v4.2.1-linux-armv7l.tar.gz.2
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Pictures
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Public
drwxrwxr-x 2 pi pi     4096 Jan  1  1970 python_games
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Templates
drwxr-xr-x 2 pi pi     4096 Sep 24 17:33 Videos

**Comment by cflurin** [comment]
go to the wiki -> "Install Avahi" and follow the guide step by step.

**Comment by ekwarg** [comment]
Thanks a lot for that and for your patience. Seems to work so far.

How do I do that part? 

"Download "config-fake.json" to the homebridge folder and "FakeOutlet.js" to the accessories folder."

**Comment by cflurin** [comment]
1. On the right hand side just below "Clone in Desktop" it say's "Download Zip file" 
2. Download Zip File 
3. Extract the file

**Comment by ekwarg** [comment]
I have managed to validate my config.json on JSONLint, but I still get an error in output:

pi@raspberrypi ~/node-v4.2.1-linux-armv7l/homebridge $ npm run start

> homebridge@0.1.1 start /home/pi/node-v4.2.1-linux-armv7l/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/home/pi/node-v4.2.1-linux-armv7l/homebridge/app.js:43
  throw err;
  ^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at Object.<anonymous> (/home/pi/node-v4.2.1-linux-armv7l/homebridge/app.js:37:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3


And Avahi is installed.

**Comment by ekwarg** [comment]
Got it to work in the end! 
thanks a lot for your patience, you made a noob's day with all the help.

**Comment by ekwarg** [comment]
Have a last question. the mytouchhome and insteon+ apps are able to see the fake-accessory and fake-homebridge but I can't seem to get it to work with telldus live

**Comment by cflurin** [comment]
```
Homebridge is a lightweight NodeJS server you can run on your home network
that emulates the iOS HomeKit API. 
```
Does telldus live works with Homekit?

**Comment by ekwarg** [comment]
Well a telldus live platform is included in homebridge. I add the platform to config.json (originally config-dake.json) but as soon as the file is modified, homebridge won't run.

**Comment by ekwarg** [comment]
*fake

**Comment by cflurin** [comment]
You need a iOS app that support Homekit in order to use homebridge.

**Comment by ekwarg** [comment]
I have mytouchhome. But homebridhe won't run start

**Comment by cflurin** [comment]
Try EVE and again please read the wiki (Troubleshooting).

**Comment by ekwarg** [comment]
Will try Eve, but please do believe me, i have followed each step thoroughly.

**Comment by ekwarg** [comment]
I have now tried Eve, and as mytouchhome and insteon+, Eve is able to locate the "Fake Homebridge" and fake_accessory. 

But how can I get it to talk to my actual hardware? Shall I add the platform Telldus live to the Fake Homebridge config.json? 

Have tried that several times but homebridge crashes at run start if any change was made to the Fake Homebridge config.json.
