### ISSUE TITLE
How to start homebridge on startup

### ISSUE THREAD

**Issue by herious1989** [cflurin/homebridge-shims#5]
I followed your instruction and my homebridge folder is located at `/home/pi` and config file is in `/home/pi/.homebridge`

I used this set up for auto start but didn't work:

    #!/bin/sh
    ### BEGIN INIT INFO
    # Provides: homebridge
    # Required-Start:    $network $remote_fs $syslog
    # Required-Stop:     $remote_fs $syslog
    # Default-Start:     2 3 4 5
    # Default-Stop:      0 1 6
    # Short-Description: Start daemon at boot time
    # Description:       Enable service provided by daemon.
    ### END INIT INFO

    dir="/home/pi"
    cmd="DEBUG=* /usr/local/bin/homebridge"
    user="pi"

I even changed cmd to /home/pi/homebridge/bin/homebridge

**Comment by cflurin** [comment]
Homebridge-shims are obsolete, please got to: https://github.com/nfarina/homebridge or https://github.com/cflurin/homebridge-punt.
